#!/bin/bash

set -e # Exit immediately if a command exits with a non-zero status.

echo "Starting Matugen Automation Setup..."

# --- Configuration Variables ---
MATUGEN_CONFIG_DIR="$HOME/.config/matugen"
MATUGEN_TEMPLATES_DIR="$MATUGEN_CONFIG_DIR/templates"
ALACRITTY_CONFIG_DIR="$HOME/.config/alacritty"
GTK3_CONFIG_DIR="$HOME/.config/gtk-3.0"
GTK4_CONFIG_DIR="$HOME/.config/gtk-4.0"
OMARCHY_BACKGROUND_SYMLINK="$HOME/.config/omarchy/current/background"
WATCHER_SCRIPT_PATH="$HOME/matugen_wallpaper_watcher.sh"
SYSTEMD_USER_DIR="$HOME/.config/systemd/user"
SYSTEMD_SERVICE_NAME="matugen-wallpaper-watcher.service"

# --- 1. Install matugen-bin and inotify-tools ---
printf "\n1. Checking and installing matugen-bin and inotify-tools...\n"
if command -v yay &> /dev/null;
then
    echo "yay found. Proceeding with package checks..."

    if ! command -v matugen &> /dev/null; then
        echo "matugen-bin not found. Installing..."
        yay -S --noconfirm matugen-bin
    else
        echo "matugen-bin is already installed."
    fi

    if ! command -v inotifywait &> /dev/null; then
        echo "inotify-tools not found. Installing..."
        yay -S --noconfirm inotify-tools
    else
        echo "inotify-tools is already installed."
    fi
else
    echo "yay not found. Please install yay or install matugen-bin and inotify-tools manually."
    exit 1
fi

# --- 2. Create necessary directories ---
printf "\n2. Creating necessary directories...\n"
mkdir -p "$MATUGEN_TEMPLATES_DIR"
mkdir -p "$ALACRITTY_CONFIG_DIR"
mkdir -p "$GTK3_CONFIG_DIR"
mkdir -p "$GTK4_CONFIG_DIR"
mkdir -p "$SYSTEMD_USER_DIR"

# --- 3. Create matugen config file (config.toml) ---
printf "\n3. Creating matugen config.toml...\n"
cat << EOF > "$MATUGEN_CONFIG_DIR/config.toml"
[config]
# Global configuration settings can go here
# reload_apps = true
# set_wallpaper = true

[templates.alacritty]
input_path = '$MATUGEN_TEMPLATES_DIR/alacritty.toml.hbs'
output_path = '$ALACRITTY_CONFIG_DIR/colors.toml'

[templates.gtk3]
input_path = '$MATUGEN_TEMPLATES_DIR/gtk.css.hbs'
output_path = '$GTK3_CONFIG_DIR/gtk.css'

[templates.gtk4]
input_path = '$MATUGEN_TEMPLATES_DIR/gtk.css.hbs'
output_path = '$GTK4_CONFIG_DIR/gtk.css'
EOF

# --- 4. Creating Alacritty template ---
printf "\n4. Creating Alacritty template...\n"
cat << 'EOF' > "$MATUGEN_TEMPLATES_DIR/alacritty.toml.hbs"
# Colors (generated by matugen)
[colors.primary]
background = '{{colors.background.dark.hex}}'
foreground = '{{colors.on_background.dark.hex}}'

[colors.normal]
black =   '{{colors.surface_container_lowest.dark.hex}}'
red =     '{{colors.error.dark.hex}}'
green =   '{{colors.primary.dark.hex}}'
yellow =  '{{colors.secondary.dark.hex}}'
blue =    '{{colors.primary_fixed.dark.hex}}'
magenta = '{{colors.tertiary.dark.hex}}'
cyan =    '{{colors.secondary_fixed.dark.hex}}'
white =   '{{colors.on_surface.dark.hex}}'

[colors.bright]
black =   '{{colors.surface_container_low.dark.hex}}'
red =     '{{colors.error_container.dark.hex}}'
green =   '{{colors.primary_container.dark.hex}}'
yellow =  '{{colors.secondary_container.dark.hex}}'
blue =    '{{colors.primary_fixed_dim.dark.hex}}'
magenta = '{{colors.tertiary_container.dark.hex}}'
cyan =    '{{colors.secondary_fixed_dim.dark.hex}}'
white =   '{{colors.surface_bright.dark.hex}}'
EOF

# --- 5. Create GTK template ---
printf "\n5. Creating GTK template...\n"
cat << 'EOF' > "$MATUGEN_TEMPLATES_DIR/gtk.css.hbs"
/* GTK Colors (generated by matugen) */

@define-color background_dark {{colors.background.dark.hex}};
@define-color on_background_dark {{colors.on_background.dark.hex}};
@define-color primary_dark {{colors.primary.dark.hex}};
@define-color on_primary_dark {{colors.on_primary.dark.hex}};
@define-color primary_container_dark {{colors.primary_container.dark.hex}};
@define-color on_primary_container_dark {{colors.on_primary_container.dark.hex}};
@define-color secondary_dark {{colors.secondary.dark.hex}};
@define-color on_secondary_dark {{colors.on_secondary.dark.hex}};
@define-color secondary_container_dark {{colors.secondary_container.dark.hex}};
@define-color on_secondary_container_dark {{colors.on_secondary_container.dark.hex}};
@define-color tertiary_dark {{colors.tertiary.dark.hex}};
@define-color on_tertiary_dark {{colors.on_tertiary.dark.hex}};
@define-color tertiary_container_dark {{colors.tertiary_container.dark.hex}};
@define-color on_tertiary_container_dark {{colors.on_tertiary_container.dark.hex}};
@define-color error_dark {{colors.error.dark.hex}};
@define-color on_error_dark {{colors.on_error.dark.hex}};
@define-color error_container_dark {{colors.error_container.dark.hex}};
@define-color on_error_container_dark {{colors.on_error_container.dark.hex}};
@define-color surface_dark {{colors.surface.dark.hex}};
@define-color on_surface_dark {{colors.on_surface.dark.hex}};
@define-color surface_variant_dark {{colors.surface_variant.dark.hex}};
@define-color on_surface_variant_dark {{colors.on_surface_variant.dark.hex}};
@define-color outline_dark {{colors.outline.dark.hex}};
@define-color inverse_primary_dark {{colors.inverse_primary.dark.hex}};
@define-color inverse_surface_dark {{colors.inverse_surface.dark.hex}};
@define-color inverse_on_surface_dark {{colors.inverse_on_surface.dark.hex}};
@define-color scrim_dark {{colors.scrim.dark.hex}};
@define-color shadow_dark {{colors.shadow.dark.hex}};
@define-color surface_tint_dark {{colors.surface_tint.dark.hex}};
@define-color background_light {{colors.background.light.hex}};
@define-color on_background_light {{colors.on_background.light.hex}};
@define-color primary_light {{colors.primary.light.hex}};
@define-color on_primary_light {{colors.on_primary.light.hex}};
@define-color primary_container_light {{colors.primary_container.light.hex}};
@define-color on_primary_container_light {{colors.on_primary_container.light.hex}};
@define-color secondary_light {{colors.secondary.light.hex}};
@define-color on_secondary_light {{colors.on_secondary.light.hex}};
@define-color secondary_container_light {{colors.secondary_container.light.hex}};
@define-color on_secondary_container_light {{colors.on_secondary_container.light.hex}};
@define-color tertiary_light {{colors.tertiary.light.hex}};
@define-color on_tertiary_light {{colors.on_tertiary.light.hex}};
@define-color tertiary_container_light {{colors.tertiary_container.light.hex}};
@define-color on_tertiary_container_light {{colors.on_tertiary_container.light.hex}};
@define-color error_light {{colors.error.light.hex}};
@define-color on_error_light {{colors.on_error.light.hex}};
@define-color error_container_light {{colors.error_container.light.hex}};
@define-color on_error_container_light {{colors.on_error_container.light.hex}};
@define-color surface_light {{colors.surface.light.hex}};
@define-color on_surface_light {{colors.on_surface.light.hex}};
@define-color surface_variant_light {{colors.surface_variant.light.hex}};
@define-color on_surface_variant_light {{colors.on_surface_variant.light.hex}};
@define-color outline_light {{colors.outline.light.hex}};
@define-color inverse_primary_light {{colors.inverse_primary.light.hex}};
@define-color inverse_surface_light {{colors.inverse_surface.light.hex}};
@define-color inverse_on_surface_light {{colors.inverse_on_surface.light.hex}};
@define-color scrim_light {{colors.scrim.light.hex}};
@define-color shadow_light {{colors.shadow.light.hex}};
@define-color surface_tint_light {{colors.surface_tint.light.hex}};
EOF

# --- 6. Create the wallpaper watcher script ---
printf '\n6. Creating wallpaper watcher script (%s)...\n' "$WATCHER_SCRIPT_PATH"
cat << 'EOF' > "$WATCHER_SCRIPT_PATH"
#!/bin/bash

CONFIG_FILE="$HOME/.config/matugen/config.toml"
SYMLINK_PATH="$HOME/.config/omarchy/current/background"

echo "Starting Matugen Wallpaper Watcher..."
echo "Monitoring: $SYMLINK_PATH"

while true; do
    # Wait for changes to the symlink
    inotifywait -e modify,create,delete,moved_to "$SYMLINK_PATH"

    # Resolve the symlink to get the actual wallpaper path
    WALLPAPER_PATH=$(readlink -f "$SYMLINK_PATH")

    if [ -f "$WALLPAPER_PATH" ]; then
        echo "Wallpaper changed to: $WALLPAPER_PATH"
        echo "Running matugen..."
        matugen image "$WALLPAPER_PATH" --config "$CONFIG_FILE"
        echo "matugen finished."

        # Optional: Add commands to reload applications here if matugen's config.toml doesn't handle it
        # For example, to restart Alacritty and Nautilus:
        # killall alacritty
        # killall nautilus

    else
        echo "Wallpaper path ($WALLPAPER_PATH) is not a valid file. Skipping matugen."
    fi

    # Add a small delay to prevent excessive runs if multiple changes occur rapidly
    sleep 2
done
EOF
chmod +x "$WATCHER_SCRIPT_PATH"

# --- 7. Create systemd service file ---
printf '\n7. Creating systemd service file (%s/%s)...\n' "$SYSTEMD_USER_DIR" "$SYSTEMD_SERVICE_NAME"
cat << EOF > "$SYSTEMD_USER_DIR/$SYSTEMD_SERVICE_NAME"
[Unit]
Description=Matugen Wallpaper Watcher
After=network-online.target graphical-session.target

[Service]
ExecStart=$WATCHER_SCRIPT_PATH
Restart=on-failure
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=graphical-session.target
EOF

# --- 8. Enable and start systemd service ---
printf "\n8. Enabling and starting systemd service...\n"
systemctl --user daemon-reload
systemctl --user enable "$SYSTEMD_SERVICE_NAME"
systemctl --user start "$SYSTEMD_SERVICE_NAME"

# --- 9. Initial matugen run ---
printf "\n9. Performing initial matugen run...\n"
INITIAL_WALLPAPER_PATH=$(readlink -f "$OMARCHY_BACKGROUND_SYMLINK")
if [ -f "$INITIAL_WALLPAPER_PATH" ]; then
    echo "Initial wallpaper: $INITIAL_WALLPAPER_PATH"
    matugen image "$INITIAL_WALLPAPER_PATH" --config "$MATUGEN_CONFIG_DIR/config.toml"
    echo "Initial matugen run complete."
else
    echo "Could not determine initial wallpaper from $OMARCHY_BACKGROUND_SYMLINK. Skipping initial matugen run."
fi

printf "\nSetup Complete!\n"
printf "\n--- Important Next Steps ---\n"
echo "1. Add the following line to your ~/.config/alacritty/alacritty.toml file (preferably at the top):"
echo "   import:"
echo "     - $ALACRITTY_CONFIG_DIR/colors.toml"
echo "   If you have an existing 'colors:' section, remove or comment it out."

printf "\n2. Restart Alacritty to see the new colors.\n"

printf "\n3. For GTK applications (like Nautilus), restart them or log out and log back in to your desktop session.\n"

printf "\n4. The matugen wallpaper watcher service is now running in the background and will automatically update colors when your wallpaper changes.\n"
