[preferred]
default=gtk
org.freedesktop.impl.portal.FileChooser=gtk
org.freedesktop.impl.portal.AppChooser=gtk
org.freedesktop.impl.portal.Screenshot=gtk
org.freedesktop.impl.portal.Screencast=gtk
org.freedesktop.impl.portal.RemoteDesktop=gtk
org.freedesktop.impl.portal.Inhibit=gtk
